### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by mlocati**
Multiple improvements here:

1. check the data specified by users when they add/edit the block
2. don't ask for useless data when add/edit block (that is, hide `tabTitle` and `semantic` input fields when adding a `close` block)
3. allow customizing the list of allowed HTML tags (the value of the `semantic` field)
4. some fixes so that my [IDE](https://www.eclipse.org/pdt/) doesn't warn me about undefined variables
5. translate the texts `<Tab Name> opening block` and `Closing block`
6. add support for multiple tabs in the same page (we assume that opening/closing blocks in the same `div` element are for the same tab set - so users can add multiple tab sets in different page areas)
7. add support for grid framework

### CODE REVIEW

**Comment by mlocati** [comment]
Here's a quick preview of what can be done with the improvements of this pull request:

quick-tabs-improvements

**Comment by mlocati** [comment]
@mg-tfg / @brucewyne are you going to review this pull requests soon?
Sorry to bother you, but I'd need these fixes ASAP...
(otherwise I'd have to fork that project, but that'd be a waste of time for both of us...)

**Comment by mlocati** [comment]
With d2c65600224293ff87fec1dfa06a848186944050 the closing block is optional.
So, a tab contents ends when one of these conditions is met (the one that happens first):

1. Users place a "closing tab" block
1. The code detects the start of another tab
1. The end of the element (for example, a `<div>`) that contains the "opening tab" block

**Comment by cristi-78** [comment]
> 
> 
> Here's a quick preview of what can be done with the improvements of this pull request:
> 
> quick-tabs-improvements

@mlocati could you, please, post that page containing multiple nested tabs in edit mode?
I tried to replicate your example but with no success.

Thanks.

**Comment by mlocati** [comment]
> could you, please, post that page containing multiple nested tabs in edit mode?

@cristi-78 what do you mean with "post that page"?

> I tried to replicate your example but with no success.

Did you apply [these changes](https://github.com/VividWeb/quick_tabs/pull/3/files)?

**Comment by cristi-78** [comment]
Sorry for not being explicit.
I want, if possible, a screenshot with that page in edit mode in order for me to see the layouts and the arrangement of blocks within them.

I used the quicktabs-improvements branch from your fork (so I believe everything should work ok)  but I replied here because of that screenshot.

Thanks..

**Comment by HamedDarragi** [comment]
@mlocati I don't think that this PR will be merged, it seems that VividWeb no longer interested in C5  http://isitvivid.com/ :-)

**Comment by mlocati** [comment]
@cristi-78 Sure! Here it is:



In order to add a nested tab set, you have to add a new 1-column layout (the one marked in red in the screenshot above.

**Comment by mlocati** [comment]
> @mlocati I don't think that this PR will be merged, it seems that VividWeb no longer interested in C5 http://isitvivid.com/ :)

Yep, we could create a fork of this repository, rename it to something else and re-submit it to the concrete5 marketplace. But for that we'd need the authorization from @brucewyne (which isn't giving any feedback).

**Comment by mlocati** [comment]
Here's a screen recording about how nested tabs behave when resizing the window (the red box is the nested layout I [described above](https://github.com/VividWeb/quick_tabs/pull/3#issuecomment-628005847)):

**Comment by HamedDarragi** [comment]
@mlocati Do we really an authorization ? it's under the MIT license.

**Comment by mlocati** [comment]
Whoops, you are right @HamedDarragi 

Of course it'd be fine to get a feedback from @brucewyne, but it's legal to fork this package and resubmit it to the marketplace.

I'll do that in the next few days.

**Comment by brucewyne** [comment]
Hey guys - I can merge this and resubmit it. I also have zero clue what/who isitvivid.com is these days (not me anymore, for sure)

**Comment by cristi-78** [comment]
Thanks, @mlocati 
Also, is good to see some action around this little package :)

**Pull request merged**
